name: Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']

    steps:
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-stable --no-progress --no-interaction

    - name: Run static analysis
      run: ./vendor/bin/phpstan analyse src

    - name: Run test suite
      run: ./vendor/bin/codecept run --quiet --no-colors --no-interaction --coverage --coverage-xml

    - name: Run mutation tests
      run: ./vendor/bin/infection --min-covered-msi=70 --threads=2 --no-progress --no-interaction --log-verbosity=none
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

    - name: Run Coveralls reporting
      run: ./vendor/bin/php-coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

