name: Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-stable --no-progress --no-interaction --quiet

    - name: Run static analysis
      run: ./vendor/bin/phpstan analyse src

    - name: Run test suite
      run: ./vendor/bin/codecept run --quiet --no-colors --no-interaction --coverage --coverage-xml

    - name: Run mutation tests
      run: ./vendor/bin/infection --min-covered-msi=80 --threads=2 --no-progress --no-interaction --log-verbosity=none
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

    - name: Run Coveralls reporting
      run: ./vendor/bin/php-coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

